# Generated by Django 4.2.24 on 2025-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_category',
            field=models.CharField(blank=True, help_text='예: 경제, 암호화폐, 시황 등. 비워도 됩니다.', max_length=40, verbose_name='카테고리 라벨'),
        ),
    ]
